#!/bin/bash

path="~/dwmsetup/scripts/pmenu/"

pmenu(){
    local option;
    option=$(echo -e "poweroff\nreboot\nlogout\nhibernate\nsleep\ncancel" | dmenu);
    if [ "$option" != "cancel" ]; then
        exec "$path/$option"
    fi    
}

pmenu
